### ISSUE TITLE
Strange Item Load

### ISSUE THREAD

**Issue by piefish1996** [Pronyo-Chan/paper-mario-randomizer-web-app#36]
So for some reason, I had this item generate on my seed. I think it's the gift the Shiver City mayor gives to the Sherlock guy? It also doesn't seem to act as a proper item, as even if I "make space" in inventory it disappears. 
Seed 4263041241 if it helps.
![Randomizer Issue](https://github.com/Pronyo-Chan/paper-mario-randomizer-web-app/assets/145583792/aaa498fe-3e0f-4f33-b821-771a550fb880)

Edit: Doesn't seem to be exclusive to this seed, also had it generate in seed 1060912647

**Comment by Pronyo-Chan** [comment]
Hi there! Thank you for the report, it seems that the latest update has an issue when combining some specific settings. We're investigating at the moment, your seed ids should be a great help to figure it out!

Thank you

**Comment by Pronyo-Chan** [comment]
We have just deployed a hotfix adressing the issue on the generator repo: https://github.com/icebound777/PMR-SeedGenerator/pull/98 (We have seperate repos for the python generator and the WebUI).

You should be able to generate new seeds with your settings and not encounter any issue. Thanks again!
